#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 25 12:30:08 2019

@author: prawigya
"""


from pandas import read_csv
#from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier

#load data
filename = 'diabetes.csv'
#names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename)

array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

#Feature extraction

model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)

