#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 25 12:55:03 2019

@author: prawigya
"""

from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

#load data
filename = 'diabetes.csv'
#names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename)

array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
test_size = 0.33
seed = 1
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
model = LogisticRegression()
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
print("Accuracy= ", result*100.0)
print()

#Accuracy is less because the data is not normalized